// Code generated by ent, DO NOT EDIT.

package episode

const (
	// Label holds the string label denoting the episode type in the database.
	Label = "episode"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTconst holds the string denoting the tconst field in the database.
	FieldTconst = "tconst"
	// FieldParentTconst holds the string denoting the parenttconst field in the database.
	FieldParentTconst = "parent_tconst"
	// FieldSeasonNumber holds the string denoting the seasonnumber field in the database.
	FieldSeasonNumber = "season_number"
	// FieldEpisodeNumber holds the string denoting the episodenumber field in the database.
	FieldEpisodeNumber = "episode_number"
	// Table holds the table name of the episode in the database.
	Table = "episodes"
)

// Columns holds all SQL columns for episode fields.
var Columns = []string{
	FieldID,
	FieldTconst,
	FieldParentTconst,
	FieldSeasonNumber,
	FieldEpisodeNumber,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SeasonNumberValidator is a validator for the "seasonNumber" field. It is called by the builders before save.
	SeasonNumberValidator func(int) error
	// EpisodeNumberValidator is a validator for the "episodeNumber" field. It is called by the builders before save.
	EpisodeNumberValidator func(int) error
)
