// Code generated by ent, DO NOT EDIT.

package crew

const (
	// Label holds the string label denoting the crew type in the database.
	Label = "crew"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTconst holds the string denoting the tconst field in the database.
	FieldTconst = "tconst"
	// FieldDirectors holds the string denoting the directors field in the database.
	FieldDirectors = "directors"
	// FieldWriters holds the string denoting the writers field in the database.
	FieldWriters = "writers"
	// Table holds the table name of the crew in the database.
	Table = "crews"
)

// Columns holds all SQL columns for crew fields.
var Columns = []string{
	FieldID,
	FieldTconst,
	FieldDirectors,
	FieldWriters,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
