// Code generated by ent, DO NOT EDIT.

package akas

const (
	// Label holds the string label denoting the akas type in the database.
	Label = "akas"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitleId holds the string denoting the titleid field in the database.
	FieldTitleId = "title_id"
	// FieldOrdering holds the string denoting the ordering field in the database.
	FieldOrdering = "ordering"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldTypes holds the string denoting the types field in the database.
	FieldTypes = "types"
	// FieldAttributes holds the string denoting the attributes field in the database.
	FieldAttributes = "attributes"
	// FieldIsOriginalTitle holds the string denoting the isoriginaltitle field in the database.
	FieldIsOriginalTitle = "is_original_title"
	// Table holds the table name of the akas in the database.
	Table = "akas"
)

// Columns holds all SQL columns for akas fields.
var Columns = []string{
	FieldID,
	FieldTitleId,
	FieldOrdering,
	FieldTitle,
	FieldRegion,
	FieldLanguage,
	FieldTypes,
	FieldAttributes,
	FieldIsOriginalTitle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OrderingValidator is a validator for the "ordering" field. It is called by the builders before save.
	OrderingValidator func(int) error
)
