// Code generated by ent, DO NOT EDIT.

package title

const (
	// Label holds the string label denoting the title type in the database.
	Label = "title"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTconst holds the string denoting the tconst field in the database.
	FieldTconst = "tconst"
	// FieldTitleType holds the string denoting the titletype field in the database.
	FieldTitleType = "title_type"
	// FieldPrimaryTitle holds the string denoting the primarytitle field in the database.
	FieldPrimaryTitle = "primary_title"
	// FieldOriginalTitle holds the string denoting the originaltitle field in the database.
	FieldOriginalTitle = "original_title"
	// FieldIsAdult holds the string denoting the isadult field in the database.
	FieldIsAdult = "is_adult"
	// FieldStartYear holds the string denoting the startyear field in the database.
	FieldStartYear = "start_year"
	// FieldEndYear holds the string denoting the endyear field in the database.
	FieldEndYear = "end_year"
	// FieldRuntimeMinutes holds the string denoting the runtimeminutes field in the database.
	FieldRuntimeMinutes = "runtime_minutes"
	// FieldGenre holds the string denoting the genre field in the database.
	FieldGenre = "genre"
	// Table holds the table name of the title in the database.
	Table = "titles"
)

// Columns holds all SQL columns for title fields.
var Columns = []string{
	FieldID,
	FieldTconst,
	FieldTitleType,
	FieldPrimaryTitle,
	FieldOriginalTitle,
	FieldIsAdult,
	FieldStartYear,
	FieldEndYear,
	FieldRuntimeMinutes,
	FieldGenre,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsAdult holds the default value on creation for the "isAdult" field.
	DefaultIsAdult bool
	// StartYearValidator is a validator for the "startYear" field. It is called by the builders before save.
	StartYearValidator func(int) error
	// EndYearValidator is a validator for the "endYear" field. It is called by the builders before save.
	EndYearValidator func(int) error
	// RuntimeMinutesValidator is a validator for the "runtimeMinutes" field. It is called by the builders before save.
	RuntimeMinutesValidator func(int) error
)
