// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NamesColumns holds the columns for the "names" table.
	NamesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tconst", Type: field.TypeString},
		{Name: "primary_name", Type: field.TypeString},
		{Name: "birth_year", Type: field.TypeInt},
		{Name: "death_year", Type: field.TypeInt},
	}
	// NamesTable holds the schema information for the "names" table.
	NamesTable = &schema.Table{
		Name:       "names",
		Columns:    NamesColumns,
		PrimaryKey: []*schema.Column{NamesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NamesTable,
	}
)

func init() {
}
