// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"imdb-db/ent/akas"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AkasCreate is the builder for creating a Akas entity.
type AkasCreate struct {
	config
	mutation *AkasMutation
	hooks    []Hook
}

// SetTitleId sets the "titleId" field.
func (ac *AkasCreate) SetTitleId(s string) *AkasCreate {
	ac.mutation.SetTitleId(s)
	return ac
}

// SetOrdering sets the "ordering" field.
func (ac *AkasCreate) SetOrdering(i int) *AkasCreate {
	ac.mutation.SetOrdering(i)
	return ac
}

// SetTitle sets the "title" field.
func (ac *AkasCreate) SetTitle(s string) *AkasCreate {
	ac.mutation.SetTitle(s)
	return ac
}

// SetRegion sets the "region" field.
func (ac *AkasCreate) SetRegion(s string) *AkasCreate {
	ac.mutation.SetRegion(s)
	return ac
}

// SetLanguage sets the "language" field.
func (ac *AkasCreate) SetLanguage(s string) *AkasCreate {
	ac.mutation.SetLanguage(s)
	return ac
}

// SetTypes sets the "types" field.
func (ac *AkasCreate) SetTypes(s []string) *AkasCreate {
	ac.mutation.SetTypes(s)
	return ac
}

// SetAttributes sets the "attributes" field.
func (ac *AkasCreate) SetAttributes(s []string) *AkasCreate {
	ac.mutation.SetAttributes(s)
	return ac
}

// SetIsOriginalTitle sets the "isOriginalTitle" field.
func (ac *AkasCreate) SetIsOriginalTitle(b bool) *AkasCreate {
	ac.mutation.SetIsOriginalTitle(b)
	return ac
}

// Mutation returns the AkasMutation object of the builder.
func (ac *AkasCreate) Mutation() *AkasMutation {
	return ac.mutation
}

// Save creates the Akas in the database.
func (ac *AkasCreate) Save(ctx context.Context) (*Akas, error) {
	var (
		err  error
		node *Akas
	)
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AkasMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			if node, err = ac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			if ac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ac.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ac.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Akas)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AkasMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AkasCreate) SaveX(ctx context.Context) *Akas {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AkasCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AkasCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AkasCreate) check() error {
	if _, ok := ac.mutation.TitleId(); !ok {
		return &ValidationError{Name: "titleId", err: errors.New(`ent: missing required field "Akas.titleId"`)}
	}
	if _, ok := ac.mutation.Ordering(); !ok {
		return &ValidationError{Name: "ordering", err: errors.New(`ent: missing required field "Akas.ordering"`)}
	}
	if v, ok := ac.mutation.Ordering(); ok {
		if err := akas.OrderingValidator(v); err != nil {
			return &ValidationError{Name: "ordering", err: fmt.Errorf(`ent: validator failed for field "Akas.ordering": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Akas.title"`)}
	}
	if _, ok := ac.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "Akas.region"`)}
	}
	if _, ok := ac.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "Akas.language"`)}
	}
	if _, ok := ac.mutation.Types(); !ok {
		return &ValidationError{Name: "types", err: errors.New(`ent: missing required field "Akas.types"`)}
	}
	if _, ok := ac.mutation.Attributes(); !ok {
		return &ValidationError{Name: "attributes", err: errors.New(`ent: missing required field "Akas.attributes"`)}
	}
	if _, ok := ac.mutation.IsOriginalTitle(); !ok {
		return &ValidationError{Name: "isOriginalTitle", err: errors.New(`ent: missing required field "Akas.isOriginalTitle"`)}
	}
	return nil
}

func (ac *AkasCreate) sqlSave(ctx context.Context) (*Akas, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ac *AkasCreate) createSpec() (*Akas, *sqlgraph.CreateSpec) {
	var (
		_node = &Akas{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: akas.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: akas.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.TitleId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: akas.FieldTitleId,
		})
		_node.TitleId = value
	}
	if value, ok := ac.mutation.Ordering(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: akas.FieldOrdering,
		})
		_node.Ordering = value
	}
	if value, ok := ac.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: akas.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := ac.mutation.Region(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: akas.FieldRegion,
		})
		_node.Region = value
	}
	if value, ok := ac.mutation.Language(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: akas.FieldLanguage,
		})
		_node.Language = value
	}
	if value, ok := ac.mutation.Types(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: akas.FieldTypes,
		})
		_node.Types = value
	}
	if value, ok := ac.mutation.Attributes(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: akas.FieldAttributes,
		})
		_node.Attributes = value
	}
	if value, ok := ac.mutation.IsOriginalTitle(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: akas.FieldIsOriginalTitle,
		})
		_node.IsOriginalTitle = value
	}
	return _node, _spec
}

// AkasCreateBulk is the builder for creating many Akas entities in bulk.
type AkasCreateBulk struct {
	config
	builders []*AkasCreate
}

// Save creates the Akas entities in the database.
func (acb *AkasCreateBulk) Save(ctx context.Context) ([]*Akas, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Akas, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AkasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AkasCreateBulk) SaveX(ctx context.Context) []*Akas {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AkasCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AkasCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
