// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"imdb-db/ent/crew"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Crew is the model entity for the Crew schema.
type Crew struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Tconst holds the value of the "tconst" field.
	Tconst string `json:"tconst,omitempty"`
	// Directors holds the value of the "directors" field.
	Directors []string `json:"directors,omitempty"`
	// Writers holds the value of the "writers" field.
	Writers []string `json:"writers,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Crew) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case crew.FieldDirectors, crew.FieldWriters:
			values[i] = new([]byte)
		case crew.FieldID:
			values[i] = new(sql.NullInt64)
		case crew.FieldTconst:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Crew", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Crew fields.
func (c *Crew) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case crew.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case crew.FieldTconst:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tconst", values[i])
			} else if value.Valid {
				c.Tconst = value.String
			}
		case crew.FieldDirectors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field directors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &c.Directors); err != nil {
					return fmt.Errorf("unmarshal field directors: %w", err)
				}
			}
		case crew.FieldWriters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field writers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &c.Writers); err != nil {
					return fmt.Errorf("unmarshal field writers: %w", err)
				}
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Crew.
// Note that you need to call Crew.Unwrap() before calling this method if this Crew
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Crew) Update() *CrewUpdateOne {
	return (&CrewClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the Crew entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Crew) Unwrap() *Crew {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Crew is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Crew) String() string {
	var builder strings.Builder
	builder.WriteString("Crew(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("tconst=")
	builder.WriteString(c.Tconst)
	builder.WriteString(", ")
	builder.WriteString("directors=")
	builder.WriteString(fmt.Sprintf("%v", c.Directors))
	builder.WriteString(", ")
	builder.WriteString("writers=")
	builder.WriteString(fmt.Sprintf("%v", c.Writers))
	builder.WriteByte(')')
	return builder.String()
}

// Crews is a parsable slice of Crew.
type Crews []*Crew

func (c Crews) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
