// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"imdb-db/ent/principals"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrincipalsCreate is the builder for creating a Principals entity.
type PrincipalsCreate struct {
	config
	mutation *PrincipalsMutation
	hooks    []Hook
}

// SetTconst sets the "tconst" field.
func (pc *PrincipalsCreate) SetTconst(s string) *PrincipalsCreate {
	pc.mutation.SetTconst(s)
	return pc
}

// SetOrdering sets the "ordering" field.
func (pc *PrincipalsCreate) SetOrdering(i int) *PrincipalsCreate {
	pc.mutation.SetOrdering(i)
	return pc
}

// SetNconst sets the "nconst" field.
func (pc *PrincipalsCreate) SetNconst(s string) *PrincipalsCreate {
	pc.mutation.SetNconst(s)
	return pc
}

// SetCategory sets the "category" field.
func (pc *PrincipalsCreate) SetCategory(s string) *PrincipalsCreate {
	pc.mutation.SetCategory(s)
	return pc
}

// SetJob sets the "job" field.
func (pc *PrincipalsCreate) SetJob(s string) *PrincipalsCreate {
	pc.mutation.SetJob(s)
	return pc
}

// SetCharacters sets the "characters" field.
func (pc *PrincipalsCreate) SetCharacters(s string) *PrincipalsCreate {
	pc.mutation.SetCharacters(s)
	return pc
}

// Mutation returns the PrincipalsMutation object of the builder.
func (pc *PrincipalsCreate) Mutation() *PrincipalsMutation {
	return pc.mutation
}

// Save creates the Principals in the database.
func (pc *PrincipalsCreate) Save(ctx context.Context) (*Principals, error) {
	var (
		err  error
		node *Principals
	)
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PrincipalsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			if node, err = pc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			if pc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Principals)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PrincipalsMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PrincipalsCreate) SaveX(ctx context.Context) *Principals {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PrincipalsCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PrincipalsCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PrincipalsCreate) check() error {
	if _, ok := pc.mutation.Tconst(); !ok {
		return &ValidationError{Name: "tconst", err: errors.New(`ent: missing required field "Principals.tconst"`)}
	}
	if _, ok := pc.mutation.Ordering(); !ok {
		return &ValidationError{Name: "ordering", err: errors.New(`ent: missing required field "Principals.ordering"`)}
	}
	if v, ok := pc.mutation.Ordering(); ok {
		if err := principals.OrderingValidator(v); err != nil {
			return &ValidationError{Name: "ordering", err: fmt.Errorf(`ent: validator failed for field "Principals.ordering": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Nconst(); !ok {
		return &ValidationError{Name: "nconst", err: errors.New(`ent: missing required field "Principals.nconst"`)}
	}
	if _, ok := pc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Principals.category"`)}
	}
	if _, ok := pc.mutation.Job(); !ok {
		return &ValidationError{Name: "job", err: errors.New(`ent: missing required field "Principals.job"`)}
	}
	if _, ok := pc.mutation.Characters(); !ok {
		return &ValidationError{Name: "characters", err: errors.New(`ent: missing required field "Principals.characters"`)}
	}
	return nil
}

func (pc *PrincipalsCreate) sqlSave(ctx context.Context) (*Principals, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pc *PrincipalsCreate) createSpec() (*Principals, *sqlgraph.CreateSpec) {
	var (
		_node = &Principals{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: principals.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: principals.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Tconst(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: principals.FieldTconst,
		})
		_node.Tconst = value
	}
	if value, ok := pc.mutation.Ordering(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: principals.FieldOrdering,
		})
		_node.Ordering = value
	}
	if value, ok := pc.mutation.Nconst(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: principals.FieldNconst,
		})
		_node.Nconst = value
	}
	if value, ok := pc.mutation.Category(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: principals.FieldCategory,
		})
		_node.Category = value
	}
	if value, ok := pc.mutation.Job(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: principals.FieldJob,
		})
		_node.Job = value
	}
	if value, ok := pc.mutation.Characters(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: principals.FieldCharacters,
		})
		_node.Characters = value
	}
	return _node, _spec
}

// PrincipalsCreateBulk is the builder for creating many Principals entities in bulk.
type PrincipalsCreateBulk struct {
	config
	builders []*PrincipalsCreate
}

// Save creates the Principals entities in the database.
func (pcb *PrincipalsCreateBulk) Save(ctx context.Context) ([]*Principals, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Principals, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrincipalsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PrincipalsCreateBulk) SaveX(ctx context.Context) []*Principals {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PrincipalsCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PrincipalsCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
