// Code generated by ent, DO NOT EDIT.

package ent

import (
	"imdb-db/ent/name"
	"imdb-db/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	nameFields := schema.Name{}.Fields()
	_ = nameFields
	// nameDescBirthYear is the schema descriptor for birthYear field.
	nameDescBirthYear := nameFields[2].Descriptor()
	// name.BirthYearValidator is a validator for the "birthYear" field. It is called by the builders before save.
	name.BirthYearValidator = nameDescBirthYear.Validators[0].(func(int) error)
	// nameDescDeathYear is the schema descriptor for deathYear field.
	nameDescDeathYear := nameFields[3].Descriptor()
	// name.DeathYearValidator is a validator for the "deathYear" field. It is called by the builders before save.
	name.DeathYearValidator = nameDescDeathYear.Validators[0].(func(int) error)
}
