// Code generated by ent, DO NOT EDIT.

package principals

const (
	// Label holds the string label denoting the principals type in the database.
	Label = "principals"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTconst holds the string denoting the tconst field in the database.
	FieldTconst = "tconst"
	// FieldOrdering holds the string denoting the ordering field in the database.
	FieldOrdering = "ordering"
	// FieldNconst holds the string denoting the nconst field in the database.
	FieldNconst = "nconst"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldJob holds the string denoting the job field in the database.
	FieldJob = "job"
	// FieldCharacters holds the string denoting the characters field in the database.
	FieldCharacters = "characters"
	// Table holds the table name of the principals in the database.
	Table = "principals"
)

// Columns holds all SQL columns for principals fields.
var Columns = []string{
	FieldID,
	FieldTconst,
	FieldOrdering,
	FieldNconst,
	FieldCategory,
	FieldJob,
	FieldCharacters,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OrderingValidator is a validator for the "ordering" field. It is called by the builders before save.
	OrderingValidator func(int) error
)
