// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Name is the predicate function for name builders.
type Name func(*sql.Selector)

// Title is the predicate function for title builders.
type Title func(*sql.Selector)
